package cmd

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/bkildow/wt-cli/internal/config"
	"github.com/bkildow/wt-cli/internal/git"
	"github.com/bkildow/wt-cli/internal/project"
	"github.com/bkildow/wt-cli/internal/ui"
	"github.com/spf13/cobra"
)

// Herdr plugin event names and the environment variables herdr sets when it
// runs an event hook. See https://herdr.dev/docs/socket-api/#plugin-apis.
const (
	herdrEventEnv        = "HERDR_PLUGIN_EVENT_JSON"
	herdrEventCreated    = "worktree_created"
	herdrEventRemoved    = "worktree_removed"
	herdrRemoveTimeout   = 5 * time.Minute
	herdrPluginID        = "wt"
	herdrManifestName    = "herdr-plugin.toml"
	herdrMinVersion      = "0.9.0"
	herdrPluginDirEnvVar = "WT_HERDR_PLUGIN_DIR"
	herdrStateDirEnv     = "HERDR_PLUGIN_STATE_DIR"
	herdrSetupKillWait   = 5 * time.Second
)

// herdrEvent mirrors the JSON herdr places in HERDR_PLUGIN_EVENT_JSON for
// worktree.* events. Only the fields wt needs are declared.
type herdrEvent struct {
	Event string `json:"event"`
	Data  struct {
		Workspace struct {
			WorkspaceID string `json:"workspace_id"`
			Worktree    struct {
				RepoKey      string `json:"repo_key"` // shared git dir (e.g. /proj/.bare or /proj/.git)
				RepoName     string `json:"repo_name"`
				RepoRoot     string `json:"repo_root"` // main checkout herdr resolved the repo from
				CheckoutPath string `json:"checkout_path"`
			} `json:"worktree"`
		} `json:"workspace"`
		Worktree struct {
			Path   string `json:"path"`
			Branch string `json:"branch"`
			IsBare bool   `json:"is_bare"`
		} `json:"worktree"`
		Forced bool `json:"forced"`
	} `json:"data"`
}

func newHerdrCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "herdr",
		Short: "Herdr integration",
		Long: `Commands for integrating wt with herdr (https://herdr.dev).

Herdr owns worktree creation and removal. The wt plugin hooks into herdr's
worktree.created and worktree.removed events to apply shared files and run
setup/teardown hooks from .worktree.yml, so worktrees created from herdr's
sidebar behave like ones created with 'wt add'.`,
	}

	cmd.AddCommand(newHerdrInitCmd())
	cmd.AddCommand(newHerdrHookCreatedCmd())
	cmd.AddCommand(newHerdrHookRemovedCmd())

	return cmd
}

func newHerdrInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Install the wt plugin into herdr",
		Long: `Writes the wt herdr plugin manifest and links it with 'herdr plugin link'.

The plugin is global to herdr, not per project: it fires for every worktree
herdr creates or removes and does nothing for repos without a .worktree.yml.
Run this once per machine.`,
		Args: cobra.NoArgs,
		RunE: runHerdrInit,
	}
	cmd.Flags().String("binary", "", "Path to the wt binary herdr should run (default: this executable)")
	cmd.Flags().Bool("no-link", false, "Write the manifest but do not run 'herdr plugin link'")
	return cmd
}

func newHerdrHookCreatedCmd() *cobra.Command {
	return &cobra.Command{
		Use:    "hook-worktree-created",
		Short:  "Handle herdr worktree.created event",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE:   runHerdrHookCreated,
	}
}

func newHerdrHookRemovedCmd() *cobra.Command {
	return &cobra.Command{
		Use:    "hook-worktree-removed",
		Short:  "Handle herdr worktree.removed event",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE:   runHerdrHookRemoved,
	}
}

// herdrManifest renders the plugin manifest herdr reads. wtBinary is the
// absolute path herdr should exec for each event.
func herdrManifest(wtBinary string) string {
	q := func(s string) string { return fmt.Sprintf("%q", s) }
	return fmt.Sprintf(`# Generated by 'wt herdr init'. Re-run it to update.
id = %s
name = "wt worktrees"
version = "1"
min_herdr_version = %s
description = "Apply wt shared files and run setup/teardown hooks for herdr worktrees"
platforms = ["macos", "linux"]

[[events]]
on = "worktree.created"
command = [%s, "herdr", "hook-worktree-created"]

[[events]]
on = "worktree.removed"
command = [%s, "herdr", "hook-worktree-removed"]
`, q(herdrPluginID), q(herdrMinVersion), q(wtBinary), q(wtBinary))
}

// herdrPluginDir is where 'wt herdr init' writes the manifest.
func herdrPluginDir() (string, error) {
	if dir := os.Getenv(herdrPluginDirEnvVar); dir != "" {
		return dir, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "wt", "herdr-plugin"), nil
}

func runHerdrInit(cmd *cobra.Command, _ []string) error {
	dry := IsDryRun()

	wtBinary, _ := cmd.Flags().GetString("binary")
	if wtBinary == "" {
		exe, err := os.Executable()
		if err != nil {
			return fmt.Errorf("cannot determine wt binary path: %w", err)
		}
		if resolved, err := filepath.EvalSymlinks(exe); err == nil {
			exe = resolved
		}
		wtBinary = exe
	}

	dir, err := herdrPluginDir()
	if err != nil {
		return err
	}
	manifestPath := filepath.Join(dir, herdrManifestName)

	if dry {
		ui.DryRunNotice("write " + manifestPath)
	} else {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(manifestPath, []byte(herdrManifest(wtBinary)), 0o644); err != nil {
			return fmt.Errorf("failed to write manifest: %w", err)
		}
		ui.Success("Wrote " + manifestPath)
	}

	if noLink, _ := cmd.Flags().GetBool("no-link"); noLink {
		ui.Info("Link it with: herdr plugin link " + dir)
		return nil
	}

	herdrBin, err := exec.LookPath("herdr")
	if err != nil {
		ui.Warning("herdr not found in PATH; link the plugin manually with: herdr plugin link " + dir)
		return nil
	}

	if dry {
		ui.DryRunNotice("exec: herdr plugin link " + dir)
		return nil
	}

	// Relink so an existing registration picks up the new manifest.
	unlink := exec.CommandContext(cmd.Context(), herdrBin, "plugin", "unlink", herdrPluginID)
	_ = unlink.Run() // not linked yet is fine

	link := exec.CommandContext(cmd.Context(), herdrBin, "plugin", "link", dir)
	link.Stderr = ui.Output
	if _, err := link.Output(); err != nil {
		return fmt.Errorf("herdr plugin link failed: %w", err)
	}
	ui.Success("Linked herdr plugin: " + herdrPluginID)

	ui.Info("  worktree.created -> " + wtBinary + " herdr hook-worktree-created")
	ui.Info("  worktree.removed -> " + wtBinary + " herdr hook-worktree-removed")
	ui.Info("Hook output is available via: herdr plugin log list --plugin " + herdrPluginID)
	return nil
}

// herdrHookContext is the state both event handlers need.
type herdrHookContext struct {
	event       herdrEvent
	projectRoot string
	cfg         *config.Config
}

// loadHerdrHookContext parses the event from the environment and resolves the
// wt project it belongs to. It returns (nil, nil) when the event is for a repo
// that is not a wt project, so callers can exit quietly: the plugin is global
// and fires for every repo herdr touches.
func loadHerdrHookContext(want string) (*herdrHookContext, error) {
	raw := os.Getenv(herdrEventEnv)
	if raw == "" {
		return nil, fmt.Errorf("%s is not set; this command is meant to be run by herdr as a plugin event hook", herdrEventEnv)
	}
	ev, err := parseHerdrEvent(raw)
	if err != nil {
		return nil, err
	}
	if ev.Event != want {
		return nil, fmt.Errorf("unexpected herdr event %q (want %q)", ev.Event, want)
	}
	if ev.Data.Worktree.Path == "" {
		return nil, fmt.Errorf("herdr event is missing data.worktree.path")
	}
	if ev.Data.Worktree.IsBare {
		return nil, nil
	}

	root, ok := resolveHerdrProjectRoot(ev.Data.Workspace.Worktree.RepoKey, ev.Data.Workspace.Worktree.RepoRoot)
	if !ok {
		return nil, nil
	}
	cfg, err := config.Load(root)
	if err != nil {
		return nil, fmt.Errorf("failed to load config: %w", err)
	}
	return &herdrHookContext{event: ev, projectRoot: root, cfg: cfg}, nil
}

func parseHerdrEvent(raw string) (herdrEvent, error) {
	var ev herdrEvent
	if err := json.Unmarshal([]byte(raw), &ev); err != nil {
		return herdrEvent{}, fmt.Errorf("invalid %s: %w", herdrEventEnv, err)
	}
	return ev, nil
}

// resolveHerdrProjectRoot locates the wt project for a herdr worktree event.
//
// repoKey is the shared git dir (".bare" or ".git" inside the project root),
// so its parent is the project root in both layouts wt supports. That is
// preferred over walking up from the checkout, because a checkout may itself
// contain a committed .worktree.yml (this repo does) and herdr places
// checkouts outside the project tree by default. repoRoot is the fallback.
func resolveHerdrProjectRoot(repoKey, repoRoot string) (string, bool) {
	if repoKey != "" {
		candidate := filepath.Dir(filepath.Clean(repoKey))
		if config.Exists(candidate) {
			return candidate, true
		}
	}
	if repoRoot != "" {
		if root, err := project.FindRoot(repoRoot); err == nil {
			return root, true
		}
	}
	return "", false
}

// herdrSetupPIDPath returns the file that records the PID of an in-flight
// setup for a herdr worktree. It lives in herdr's plugin state dir, not in
// the checkout, because herdr deletes the checkout before emitting
// worktree.removed and the removal handler must still be able to find and
// stop a setup that is still running.
func herdrSetupPIDPath(worktreePath string) string {
	base := os.Getenv(herdrStateDirEnv)
	if base == "" {
		base = filepath.Join(os.TempDir(), "wt-herdr")
	}
	sum := sha256.Sum256([]byte(filepath.Clean(worktreePath)))
	name := project.WorktreeIDFromBranch(filepath.Base(worktreePath)) + "-" + hex.EncodeToString(sum[:6]) + ".pid"
	return filepath.Join(base, "setup", name)
}

func writeHerdrSetupPID(worktreePath string, pid int) error {
	path := herdrSetupPIDPath(worktreePath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(strconv.Itoa(pid)), 0o644)
}

func readHerdrSetupPID(worktreePath string) (int, bool) {
	data, err := os.ReadFile(herdrSetupPIDPath(worktreePath))
	if err != nil {
		return 0, false
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil || pid <= 0 {
		return 0, false
	}
	return pid, true
}

// stopHerdrSetup terminates a setup still running for worktreePath, if any,
// and waits for it to exit so teardown does not race with provisioning.
func stopHerdrSetup(worktreePath string) {
	defer func() { _ = os.Remove(herdrSetupPIDPath(worktreePath)) }()

	pid, ok := readHerdrSetupPID(worktreePath)
	if !ok || pid == os.Getpid() || !project.IsProcessAlive(pid) {
		return
	}

	ui.Warning(fmt.Sprintf("Stopping in-progress setup (PID %d) before teardown", pid))
	_ = terminateProcess(pid)

	deadline := time.After(herdrSetupKillWait)
	tick := time.NewTicker(100 * time.Millisecond)
	defer tick.Stop()
	for {
		select {
		case <-tick.C:
			if !project.IsProcessAlive(pid) {
				return
			}
		case <-deadline:
			ui.Warning("Setup did not exit; force-killing")
			_ = killProcess(pid)
			return
		}
	}
}

func runHerdrHookCreated(cmd *cobra.Command, _ []string) error {
	hctx, err := loadHerdrHookContext(herdrEventCreated)
	if err != nil {
		return err
	}
	if hctx == nil {
		return nil // not a wt project
	}

	projectRoot, cfg := hctx.projectRoot, hctx.cfg
	worktreePath := hctx.event.Data.Worktree.Path
	branch := hctx.event.Data.Worktree.Branch

	if _, err := os.Stat(worktreePath); err != nil {
		return fmt.Errorf("worktree path from herdr does not exist: %s", worktreePath)
	}

	gitDir := project.GitDirPath(projectRoot, cfg)
	if err := project.EnsureGitExclude(gitDir, false); err != nil {
		ui.Warning("Could not configure git excludes: " + err.Error())
	}

	vars := project.NewTemplateVars(projectRoot, worktreePath, branch)

	ui.Step("Applying shared files to herdr worktree: " + worktreePath)
	result, err := project.Apply(projectRoot, worktreePath, cfg, false, &vars)
	if err != nil {
		return fmt.Errorf("apply shared files failed: %w", err)
	}

	msg := fmt.Sprintf("Prepared herdr worktree %s (%d copied, %d symlinked)",
		branch, result.Copied, result.Symlinked)

	if len(cfg.Setup) == 0 && len(cfg.ParallelSetup) == 0 {
		ui.Success(msg)
		return nil
	}

	// Herdr does not wait for event hooks, so setup runs in this process and
	// its output stays in 'herdr plugin log'. Record our PID outside the
	// checkout so the removal handler can stop us if the worktree is deleted
	// mid-setup, and stop child hooks when we are terminated.
	if err := writeHerdrSetupPID(worktreePath, os.Getpid()); err != nil {
		ui.Warning("Could not record setup PID: " + err.Error())
	}
	defer func() { _ = os.Remove(herdrSetupPIDPath(worktreePath)) }()

	ctx, stop := signal.NotifyContext(cmd.Context(), syscall.SIGTERM, syscall.SIGINT)
	defer stop()

	startedAt := time.Now()
	setupErr := project.RunSetupHooks(ctx, cfg, vars, false, nil)
	if pErr := project.RunParallelSetupHooks(ctx, cfg, vars, false); pErr != nil {
		setupErr = errors.Join(setupErr, pErr)
	}
	if ctx.Err() != nil {
		return fmt.Errorf("setup interrupted: %w", ctx.Err())
	}

	state := &project.SetupState{
		Status:         project.SetupComplete,
		StartedAt:      startedAt,
		CompletedAt:    time.Now(),
		HooksTotal:     len(cfg.Setup) + len(cfg.ParallelSetup),
		HooksCompleted: len(cfg.Setup) + len(cfg.ParallelSetup),
	}
	if setupErr != nil {
		state.Status = project.SetupFailed
		state.Error = setupErr.Error()
	}
	if err := project.WriteSetupState(worktreePath, state); err != nil {
		ui.Warning("Failed to write setup state: " + err.Error())
	}

	elapsed := ui.FormatDuration(time.Since(startedAt))
	if setupErr != nil {
		ui.Warning(msg + " — setup hooks failed after " + elapsed)
		return nil
	}
	ui.Success(msg + " — completed in " + elapsed)
	return nil
}

func runHerdrHookRemoved(cmd *cobra.Command, _ []string) error {
	ctx, cancel := context.WithTimeout(cmd.Context(), herdrRemoveTimeout)
	defer cancel()

	hctx, err := loadHerdrHookContext(herdrEventRemoved)
	if err != nil {
		return err
	}
	if hctx == nil {
		return nil // not a wt project
	}

	projectRoot, cfg := hctx.projectRoot, hctx.cfg
	worktreePath := hctx.event.Data.Worktree.Path
	branch := hctx.event.Data.Worktree.Branch

	// Always stop a setup that may still be provisioning, even when no
	// teardown is configured; otherwise it keeps running against a deleted
	// checkout.
	stopHerdrSetup(worktreePath)

	vars := project.NewTemplateVars(projectRoot, worktreePath, branch)

	if _, statErr := os.Stat(worktreePath); statErr == nil {
		// Unusual: herdr left the directory in place. Ordinary teardown is
		// safe to run inside it.
		terminateBackgroundSetup(worktreePath, branch, false)
		ui.Step("Running teardown hooks for herdr worktree: " + branch)
		if err := project.RunTeardownHooks(ctx, cfg, vars, false); err != nil {
			ui.Warning("Teardown hooks failed: " + err.Error())
		}
		if err := project.RunParallelTeardownHooks(ctx, cfg, vars, false); err != nil {
			ui.Warning("Parallel teardown hooks failed: " + err.Error())
		}
	} else {
		// Normal herdr case: worktree.removed fires after 'git worktree
		// remove', so the checkout is gone. teardown/parallel_teardown are
		// written to run inside the checkout (docker compose down, make
		// clean) and would act on the wrong directory if run anywhere else,
		// so they are skipped. post_remove hooks are the explicit opt-in for
		// this situation.
		skipped := len(cfg.Teardown) + len(cfg.ParallelTeardown)
		if skipped > 0 {
			ui.Warning(fmt.Sprintf("Worktree directory already removed by herdr; skipped %d teardown hook(s) that must run inside the worktree:", skipped))
			for _, h := range cfg.Teardown {
				ui.Info("  " + h)
			}
			for _, h := range cfg.ParallelTeardown {
				ui.Info("  " + h)
			}
			if len(cfg.PostRemove) == 0 {
				ui.Info("  Add 'post_remove' hooks to .worktree.yml to clean up resources by $WT_WORKTREE_ID.")
			}
		}
		if len(cfg.PostRemove) > 0 {
			ui.Step("Running post_remove hooks from project root for: " + branch)
			if err := project.RunPostRemoveHooks(ctx, cfg, vars, false); err != nil {
				ui.Warning("post_remove hooks failed: " + err.Error())
			}
		}
	}

	// Herdr may have removed the checkout while git still tracks it (e.g.
	// a forced removal that only deleted the directory); tidy that up.
	runner := git.NewRunner(project.GitDirPath(projectRoot, cfg), false)
	runner.BatchMode = true
	if err := runner.WorktreePrune(ctx); err != nil {
		ui.Warning("git worktree prune failed: " + err.Error())
	}

	ui.Success("Tore down herdr worktree: " + branch)
	return nil
}
